# Generated by Django 4.2.1 on 2023-05-26 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя клиента')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Телефон')),
                ('tg_username', models.CharField(max_length=30, verbose_name='Ник в телеграм')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя мастера')),
            ],
            options={
                'verbose_name': 'мастер',
                'verbose_name_plural': 'Мастера',
            },
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название процедуры')),
                ('cost', models.IntegerField(verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'процедура',
                'verbose_name_plural': 'Процедуры',
            },
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_slot', models.CharField(max_length=20, verbose_name='Временной слот')),
            ],
            options={
                'verbose_name': 'слот',
                'verbose_name_plural': 'Временные слоты',
            },
        ),
        migrations.CreateModel(
            name='MasterProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salon.master', verbose_name='Мастер')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salon.procedure', verbose_name='Процедура')),
            ],
            options={
                'verbose_name': 'процедуры мастера',
                'verbose_name_plural': 'процедуры мастеров',
            },
        ),
        migrations.AddField(
            model_name='master',
            name='procedures',
            field=models.ManyToManyField(related_name='procedure', through='salon.MasterProcedure', to='salon.procedure'),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата записи')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='salon.client', verbose_name='Клиент')),
                ('masterprocedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='salon.masterprocedure')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='salon.time', verbose_name='Время записи')),
            ],
            options={
                'verbose_name': 'запись',
                'verbose_name_plural': 'Записи на процедуры',
            },
        ),
    ]
