# Generated by Django 4.2.1 on 2023-05-27 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='masterprocedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='salon.masterprocedure', verbose_name='Мастер с процедурой'),
        ),
        migrations.AlterField(
            model_name='master',
            name='procedures',
            field=models.ManyToManyField(related_name='masters', through='salon.MasterProcedure', to='salon.procedure'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Отзыв')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='salon.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
